apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: LoadBalancer  # or LoadBalancer, based on your requirements
  ports:
    - port: 8000
      targetPort: 8000
 
  selector:
    app: django
