apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # Use NodePort if you don't have a cloud provider
  ports:
    - port: 3000
      targetPort: 80
  selector:
    app: react-app
