apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: "edunexususer"
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "edunexus"
          ports:
            - containerPort: 5432
