apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP  # Use ClusterIP to allow other pods in the cluster to connect
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
